config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new', as: :new_session
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :users

  resources :restaurants, only: [:create, :show] do
  resources :menus
  end

  resources :menus, only: [] do
    resources :dishes, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :dishes do
    resources :dish_diets, only: [:destroy]
    resources :dish_extras, only: [:index, :new, :create, :destroy]
  end
  resources :ingredients, only: [:create]

  post '/dishes/:dish_id/dish_diets/:id' => 'dish_diets#create'

  # MENU change state
  patch '/publish_menu/:id' => 'menus#publish', as: :menu_publish
  patch '/cancel_menu/:id' => 'menus#cancel', as: :menu_cancel

  # API
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :restaurants, only: [:index, :show]
    end
  end

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :menu
  has_many :dish_diets, dependent: :destroy
  has_many :diets, through: :dish_diets, dependent: :nullify
  has_many :dish_extras, dependent: :destroy
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_filter :find_dish, only: [:show, :edit, :update, :destroy]
  def create
    dish = Dish.new(
                    name: params[:name],
                    price: params[:price],
                    description: params[:description],
                    menu_id: params[:menu_id]
                  )
    dish.save!
    render nothing: true
  end

  def show
  end

  def edit
  end

  def update
    render json: params
    # @menu = Menu.find(params[:menu_id])
    # restaurant = Restaurant.find(@menu.restaurant_id)
    # @dish.update dish_params
    # redirect_to restaurant_path(restaurant)
  end

  def destroy
    menu = Menu.find(params[:menu_id])
    dish = Dish.find(params[:id])
    dish.destroy!
    redirect_to restaurant_path(menu.restaurant_id)
  end

  private
  def find_dish
    @dish = Dish.find(params[:id])
  end
end

app/views/dishes/edit.html.erb
<%= simple_form_for @dish do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/dishes/show.html.erb
<div class="container">
  <h1> <%= @dish.name %> </h1>
  <%= link_to "edit", edit_menu_dish_path(@dish.menu_id, @dish) %> | 
  <%= link_to "delete", menu_dish_path(@dish.menu_id, @dish), method: :delete, data: {confirm: "Are you sure you want to delete this dish?"} %>
  <div class="row">
    <div class="col-md-3">
      <%= simple_form_for [@dish, @dish.dish_extras.build], remote: true do |f| %>
        <%= f.input :description if f.object.id.nil? %>
        <%= f.submit %>
      <% end %>
    </div>

    <div class="col-md-9">
      Dish description: <%= @dish.description %><br>
      Dish price: <%= @dish.price %><br>

      Dish extras: <br>
      <% @dish.dish_extras.each do |extra| %>
        <% next if extra.new_record? %>
        <li>
          <%= extra.description %>
          <%= link_to dish_dish_extra_path(@dish, extra), method: :delete, data: {confirm: "Do you want to delete this extra?"}, remote: true do %>
            <span class='glyphicon glyphicon-minus'></span>
          <% end %>
        </li>
      <% end %> 
    </div>
  </div>

</div>